name: flutter_app
description: "A Flutter application built with Feature-First Clean Architecture."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.1.2
  equatable: ^2.0.7
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.2.1
  flutter_screenutil: ^5.9.3
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  go_router: ^17.1.0
  google_fonts: ^8.0.2
  hooks_riverpod: ^3.2.1
  json_annotation: ^4.11.0
  logger: ^2.6.2
  riverpod_annotation: ^4.0.2
  url_strategy: ^0.3.0

dev_dependencies:
  build_runner: ^2.11.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  riverpod_generator: ^4.0.3
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
